### ISSUE TITLE
Report Content

### ISSUE THREAD

**Issue by Dada-none** [HARl803/cscenter-service#1]
## Description
- 관리자는 컨텐츠(게시글, 댓글)을 삭제를 할 수 있도록 하고, 로그인 유저는 게시글을 조회할 수 있도록 구현합니다.

## Todo
- [x] User의 컨텐츠 신고 및 내용 단일조회 할 수 있는 `controller`를 구현합니다.
- [x]  `/api/v1/cscenter/report-content`에 매핑되는 `controller`를 구현합니다.
    - [x] User가 로그인 된 상태에서 악성 컨텐츠를 등록
    - [x] User가 로그인 된 상태에서 본인이 신고한 신고 내용을 확인 가능
    - [x] Request와 Response로 나누어 구현
- [x] 메인로직을 담은 `service`를 작성합니다.
    - [x] 신고 id를 받아 DB에 존재하면 신고자, 피신고자, 악성 컨텐츠의 내용을 조회합니다.
    - [x] 찾지 못할경우 `Exception`을 발생합니다.
    - [x] 파라미터로 받은 신고자, 피신고자, 악성 컨텐츠의 아이디로 신고를 등록합니다. 
    - [x] 악성 컨텐츠의 아이디를 찾고, 이미 존재하는 경우 `Exception`을 발생합니다.
    - [x] 신고자, 피신고자의 아이디를 찾고, 존재하지 않는 경우 `Exception`을 발생합니다.
    - [x] 3개의 문자와 1씩 증가하는 17자리 수의 16진수를 합쳐 기본키를 생성합니다. 
- [x] Admin에서도 공용으로 사용될 예정이기 때문에 common 패키지에 엔티티를 생성합니다.
