### ISSUE TITLE
Report User

### ISSUE THREAD

**Issue by Dada-none** [HARl803/cscenter-service#2]
## Description
- 관리자는 악성 유저로 인한 이슈 판단 및 페널티를 부과할 수 있도록 하고, 신고자는 신고 현황을 조회하며 피신고자는 문제가 있다고 판별 될 시 신고 내용에 대한 처분 알림을 받을 수 있도록 구현합니다.

## Todo
- [x] User의 유저 신고 및 내용을 단일조회 할 수 있는 `controller`를 구현합니다.
- [x]  `/api/v1/cscenter/report-user`에 매핑되는 `controller`를 구현합니다.
    - [x] User가 로그인 된 상태에서 악성 유저를 등록
    - [x] User가 로그인 된 상태에서 본인이 신고한 신고 내용을 확인 가능
    - [x] Request와 Response로 나누어 구현
- [x] 메인로직을 담은 `service`를 작성합니다.
    - [x] 신고 id를 받아 DB에 존재하면 신고자, 피신고자, 작성 내용(글, 이미지)의 내용을 조회합니다.
    - [x] 찾지 못 할 경우 `Exception`을 발생합니다.
    - [x] 파라미터로 받은 신고자, 피신고자, 신고 사유, 이미지(필요시)로 신고를 등록합니다. 
    - [x] 신고자, 피신고자의 아이디를 찾고, 존재하지 않는 경우 `Exception`을 발생합니다.
    - [x] 3개의 문자와 1씩 증가하는 17자리 수의 16진수를 합쳐 기본키를 생성합니다.
